module.exports = {
    Request       : require('./request'),
    Day           : require('./day'),
    Weather       : require('./weather'),
    Commands      : require('./commands'),
    Dice          : require('./dice'),
    Safeword      : require('./safeword'),
    // CharacterData : require('./characterData'),
    CharacterDataR: require('./characterDataR'),
    Downtime      : require('./downtime'),
    Helper        : require('./status'),
    SessionData   : require('./sessionData'),
    LegendKeeper  : require('./lkr'),
    Backup        : require('./backup'),
    CheckIn       : require('./checkin'),
    Prices        : require('./prices'),
};
